version: "3.8"
services:
  postgres-account:
    image: "postgres:alpine"
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - "pgdata_account:/var/lib/postgresql/data"
      # - ./init:/docker-entrypoint-initdb.d/
    command: ["postgres", "-c", "log_statement=all"]

  backend:
    build:
      context: ./backend
      target: builder
    image: backend
    ports:
      - "8000:8080"
    expose:
      - "8080"
    environment:
      - ENV=dev
    volumes:
      - ./backend:/go/src/app
    command: reflex -r "\.go$$" -s -- sh -c "go run ./"
    depends_on:
      - postgres-account

volumes:
   pgdata_account:
