CREATE TABLE IF NOT EXISTS products(
  id CHARACTER(27)  PRIMARY KEY,
  seller_id CHARACTER(27)  NOT NULL,
  name VARCHAR (50) NOT NULL,
  stock INT NOT NULL DEFAULT 0,
  category VARCHAR(50) NOT NULL,
  created_at TIMESTAMPTZ  NOT NULL DEFAULT (NOW())
);
